"""
PAC (Proxy Auto-Configuration) file generation and serving.

The PAC file tells the iOS device which requests should go through
the MITM proxy and which should go direct.
"""

from fastapi import APIRouter, Request
from fastapi.responses import PlainTextResponse

from backend.config import settings, yaml_config

router = APIRouter(tags=["pac"])


PAC_TEMPLATE = """
// Proxy Auto-Configuration for iOS Location Spoofing
// Generated by LocSpoof Service

function FindProxyForURL(url, host) {{
    // Domains that need to be intercepted by the MITM proxy
    var interceptDomains = [
        "gs-loc-cn.apple.com",
        "gs-loc.apple.com",
        "cl1-cdn.apple.com",
        "cl2-cdn.apple.com",
        "cl3-cdn.apple.com",
        "cl4-cdn.apple.com",
        "cl5-cdn.apple.com"
    ];

    for (var i = 0; i < interceptDomains.length; i++) {{
        if (dnsDomainIs(host, interceptDomains[i])) {{
            return "HTTPS {proxy_host}:{proxy_port}";
        }}
    }}

    // All other traffic goes direct
    return "DIRECT";
}}
""".strip()


def _get_proxy_host(request: Request) -> str:
    """
    Determine the proxy host address.
    In LAN mode, use the configured LAN IP.
    In domain mode, use the request host.
    """
    server_cfg = yaml_config.get("server", {})
    import os
    mode = os.environ.get("LAN_MODE") or server_cfg.get("mode", "domain")

    if mode == "lan":
        # Env vars take priority, then yaml, then settings
        api_host = os.environ.get("API_HOST") or server_cfg.get("api_host") or settings.api_host
        # Strip port if present (e.g. "192.168.1.100:8000" -> "192.168.1.100")
        return api_host.split(":")[0]

    # Domain mode: use the request's host header
    return request.headers.get("host", settings.api_host).split(":")[0]


@router.get("/proxy.pac")
async def serve_pac(request: Request):
    """
    Serve the PAC file.
    The proxy host/port should point to the MITM proxy server.
    """
    proxy_host = _get_proxy_host(request)
    proxy_port = yaml_config.get("ports", {}).get("proxy", 8443)

    pac_content = PAC_TEMPLATE.format(
        proxy_host=proxy_host,
        proxy_port=proxy_port,
    )

    return PlainTextResponse(
        content=pac_content,
        media_type="application/x-ns-proxy-autoconfig",
        headers={
            "Cache-Control": "no-cache, no-store, must-revalidate",
            "Pragma": "no-cache",
        },
    )
