#!/bin/bash
# ============================================================
# VMware Linux VM - VPN Server Quick Setup
# ============================================================
# Prerequisites:
#   - Docker + Docker Compose installed
#   - VM network adapter set to Bridged mode (gets LAN IP)
#   - A shared folder between Windows host and this VM
#     (or you can scp the certs manually)
#
# Usage:
#   bash setup.sh                              # Auto-detect VM IP
#   bash setup.sh 192.168.1.XX                 # Manual VM IP
#   bash setup.sh 192.168.1.XX /shared/certs   # With shared certs dir
# ============================================================

set -e

# --- Detect / accept VM IP ---
if [ -n "$1" ]; then
    VM_IP="$1"
else
    VM_IP=$(ip -4 route get 8.8.8.8 2>/dev/null | awk '{print $7; exit}')
    [ -z "$VM_IP" ] && VM_IP=$(hostname -I | awk '{print $1}')
fi

if [ -z "$VM_IP" ]; then
    echo "[!] Could not detect VM IP."
    echo "    Usage: bash setup.sh <VM_LAN_IP> [certs_dir]"
    exit 1
fi

# --- Certs directory ---
if [ -n "$2" ]; then
    CERTS_DIR="$2"
else
    CERTS_DIR="$(pwd)/certs"
fi

echo ""
echo "============================================"
echo "  LocSpoof VPN Server (VMware Linux)"
echo "============================================"
echo "  VM LAN IP:   $VM_IP"
echo "  Certs Dir:   $CERTS_DIR"
echo "============================================"
echo ""

# Navigate to script directory
cd "$(dirname "$0")"

# Create certs dir if it doesn't exist
mkdir -p "$CERTS_DIR"

# Write .env
cat > .env << EOF
VPN_HOST=$VM_IP
VPN_USERNAME=user@locspoof.local
VPN_PASSWORD=changeme
CERTS_DIR=$CERTS_DIR
EOF

echo "[+] Created .env"

# Build and start
echo "[+] Building Docker image (first time may take 1-2 min)..."
docker compose build --quiet

echo "[+] Starting VPN server..."
docker compose up -d

# Wait for init
echo "[*] Waiting for startup..."
sleep 5

# Check status
if docker compose ps | grep -q "running"; then
    echo ""
    echo "============================================"
    echo "  VPN Server Running!"
    echo "============================================"
    echo ""
    echo "  VPN Host:    $VM_IP"
    echo "  Type:        IKEv2"
    echo "  Username:    user@locspoof.local"
    echo "  Password:    changeme"
    echo ""

    if [ -f "$CERTS_DIR/ca.cer" ]; then
        echo "  [+] CA cert available: $CERTS_DIR/ca.cer"
    fi

    echo ""
    echo "  --- On Windows ---"
    echo "  1. Make sure $CERTS_DIR has ca.crt and ca.cer"
    echo "     (either from this VM or generated by"
    echo "      python scripts/generate_ca.py on Windows)"
    echo ""
    echo "  2. Update config/config.yaml:"
    echo "     vpn_host: $VM_IP"
    echo "     api_host: <WINDOWS_LAN_IP>:8000"
    echo ""
    echo "  3. Start API + Proxy on Windows:"
    echo "     python run.py"
    echo "     python run.py proxy"
    echo ""
    echo "  --- On iPhone ---"
    echo "  4. Safari: http://<WINDOWS_IP>:8000/install.mobileconfig"
    echo "  5. Settings > Install profile"
    echo "  6. Settings > General > About > Cert Trust > Enable CA"
    echo "  7. Settings > VPN > Enable"
    echo "  8. http://<WINDOWS_IP>:8000/ > Select location > Apply"
    echo ""
    echo "  Logs:  docker compose logs -f"
    echo "  Stop:  docker compose down"
    echo "============================================"
else
    echo "[!] Container may not be running. Check logs:"
    echo "    docker compose logs"
fi
